# Generated by Django 5.0.3 on 2024-05-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
