# Generated by Django 5.0.3 on 2024-03-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_usercarrito_email_alter_usercarrito_usuario'),
        ('Usuarios', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarrito',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
    ]
