# Generated by Django 5.0.3 on 2024-03-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_usercarrito_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercarrito',
            name='usuario',
        ),
    ]
