# Generated by Django 5.0.3 on 2024-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_remove_usercarrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemcarrito',
            name='imagen_producto',
            field=models.ImageField(default='default.jpg', upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='useritemcarrito',
            name='nombre_producto',
            field=models.CharField(default='Nombre Producto', max_length=100),
        ),
        migrations.AddField(
            model_name='useritemcarrito',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
