# Generated by Django 5.0.3 on 2024-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_useritemcarrito_imagen_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritemcarrito',
            name='usuario_id',
            field=models.IntegerField(default=0),
        ),
    ]
